SHELL = cmd.exe

#
# ZDS II Make File - many_sprites project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sprites\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sprites;..\..\..\..\..\Includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\many_sprites_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sprites\Debug

build: many_sprites

buildall: clean many_sprites

relink: deltarget many_sprites

deltarget: 
	@if exist $(WORKDIR)\many_sprites.lod  \
            $(RM) $(WORKDIR)\many_sprites.lod
	@if exist $(WORKDIR)\many_sprites.hex  \
            $(RM) $(WORKDIR)\many_sprites.hex
	@if exist $(WORKDIR)\many_sprites.map  \
            $(RM) $(WORKDIR)\many_sprites.map

clean: 
	@if exist $(WORKDIR)\many_sprites.lod  \
            $(RM) $(WORKDIR)\many_sprites.lod
	@if exist $(WORKDIR)\many_sprites.hex  \
            $(RM) $(WORKDIR)\many_sprites.hex
	@if exist $(WORKDIR)\many_sprites.map  \
            $(RM) $(WORKDIR)\many_sprites.map
	@if exist $(WORKDIR)\sprites.obj  \
            $(RM) $(WORKDIR)\sprites.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\sprites.obj

many_sprites: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\sprites.obj :  \
            E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sprites\src\sprites.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sprites\src\sprites.asm

