SHELL = cmd.exe

#
# ZDS II Make File - opcodes project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\opcodes\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"..;$(INCLUDE)\std;$(INCLUDE)\zilog" -list -NOlistmac  \
-name -pagelen:56 -pagewidth:80 -quiet -sdiopt -warn -debug  \
-NOigcase -cpu:eZ80L92

LDFLAGS = @.\opcodes_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\opcodes\Debug

build: opcodes

buildall: clean opcodes

relink: deltarget opcodes

deltarget: 
	@if exist $(WORKDIR)\opcodes.lod  \
            $(RM) $(WORKDIR)\opcodes.lod
	@if exist $(WORKDIR)\opcodes.hex  \
            $(RM) $(WORKDIR)\opcodes.hex
	@if exist $(WORKDIR)\opcodes.map  \
            $(RM) $(WORKDIR)\opcodes.map

clean: 
	@if exist $(WORKDIR)\opcodes.lod  \
            $(RM) $(WORKDIR)\opcodes.lod
	@if exist $(WORKDIR)\opcodes.hex  \
            $(RM) $(WORKDIR)\opcodes.hex
	@if exist $(WORKDIR)\opcodes.map  \
            $(RM) $(WORKDIR)\opcodes.map
	@if exist $(WORKDIR)\opcodes.obj  \
            $(RM) $(WORKDIR)\opcodes.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\opcodes.obj

opcodes: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\opcodes.obj :  \
            E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\opcodes\source\opcodes.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\opcodes\source\opcodes.asm

