SHELL = cmd.exe

#
# ZDS II Make File - joystick project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\JOYSTI~1\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"..;E:\My_Own_Files\Coding\Ez80 Project\Code\PROSE Apps\includes;..\..\..\includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\joystick_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\JOYSTI~1\Debug

build: joystick

buildall: clean joystick

relink: deltarget joystick

deltarget: 
	@if exist $(WORKDIR)\joystick.lod  \
            $(RM) $(WORKDIR)\joystick.lod
	@if exist $(WORKDIR)\joystick.hex  \
            $(RM) $(WORKDIR)\joystick.hex
	@if exist $(WORKDIR)\joystick.map  \
            $(RM) $(WORKDIR)\joystick.map

clean: 
	@if exist $(WORKDIR)\joystick.lod  \
            $(RM) $(WORKDIR)\joystick.lod
	@if exist $(WORKDIR)\joystick.hex  \
            $(RM) $(WORKDIR)\joystick.hex
	@if exist $(WORKDIR)\joystick.map  \
            $(RM) $(WORKDIR)\joystick.map
	@if exist $(WORKDIR)\joystick.obj  \
            $(RM) $(WORKDIR)\joystick.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\joystick.obj

joystick: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\joystick.obj :  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\JOYSTI~1\src\joystick.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\JOYSTI~1\src\joystick.asm

