SHELL = cmd.exe

#
# ZDS II Make File - comsend project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\comsend\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"..;..\..\..\Includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\comsend_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\comsend\Debug

build: comsend

buildall: clean comsend

relink: deltarget comsend

deltarget: 
	@if exist $(WORKDIR)\comsend.lod  \
            $(RM) $(WORKDIR)\comsend.lod
	@if exist $(WORKDIR)\comsend.hex  \
            $(RM) $(WORKDIR)\comsend.hex
	@if exist $(WORKDIR)\comsend.map  \
            $(RM) $(WORKDIR)\comsend.map

clean: 
	@if exist $(WORKDIR)\comsend.lod  \
            $(RM) $(WORKDIR)\comsend.lod
	@if exist $(WORKDIR)\comsend.hex  \
            $(RM) $(WORKDIR)\comsend.hex
	@if exist $(WORKDIR)\comsend.map  \
            $(RM) $(WORKDIR)\comsend.map
	@if exist $(WORKDIR)\comsend.obj  \
            $(RM) $(WORKDIR)\comsend.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\comsend.obj

comsend: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\comsend.obj :  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\comsend\src\comsend.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\comsend\src\comsend.asm

