SHELL = cmd.exe

#
# ZDS II Make File - memtest project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\memtest\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"..;..\..\..\Includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\memtest_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\memtest\Debug

build: memtest

buildall: clean memtest

relink: deltarget memtest

deltarget: 
	@if exist $(WORKDIR)\memtest.lod  \
            $(RM) $(WORKDIR)\memtest.lod
	@if exist $(WORKDIR)\memtest.hex  \
            $(RM) $(WORKDIR)\memtest.hex
	@if exist $(WORKDIR)\memtest.map  \
            $(RM) $(WORKDIR)\memtest.map

clean: 
	@if exist $(WORKDIR)\memtest.lod  \
            $(RM) $(WORKDIR)\memtest.lod
	@if exist $(WORKDIR)\memtest.hex  \
            $(RM) $(WORKDIR)\memtest.hex
	@if exist $(WORKDIR)\memtest.map  \
            $(RM) $(WORKDIR)\memtest.map
	@if exist $(WORKDIR)\memtest.obj  \
            $(RM) $(WORKDIR)\memtest.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\memtest.obj

memtest: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\memtest.obj :  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\memtest\src\memtest.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\memtest\src\memtest.asm

