SHELL = cmd.exe

#
# ZDS II Make File - relative project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\RELATI~1\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\RELATI~1;..\..\..\..\..\Includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\relative_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\RELATI~1\Debug

build: relative

buildall: clean relative

relink: deltarget relative

deltarget: 
	@if exist $(WORKDIR)\relative.lod  \
            $(RM) $(WORKDIR)\relative.lod
	@if exist $(WORKDIR)\relative.hex  \
            $(RM) $(WORKDIR)\relative.hex
	@if exist $(WORKDIR)\relative.map  \
            $(RM) $(WORKDIR)\relative.map

clean: 
	@if exist $(WORKDIR)\relative.lod  \
            $(RM) $(WORKDIR)\relative.lod
	@if exist $(WORKDIR)\relative.hex  \
            $(RM) $(WORKDIR)\relative.hex
	@if exist $(WORKDIR)\relative.map  \
            $(RM) $(WORKDIR)\relative.map
	@if exist $(WORKDIR)\relative.obj  \
            $(RM) $(WORKDIR)\relative.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\relative.obj

relative: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\relative.obj :  \
            E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\RELATI~1\src\relative.asm  \
            E:\My_Own_Files\Coding\ez80p\Code\Includes\amoeba_hardware_equates.asm  \
            E:\My_Own_Files\Coding\ez80p\Code\Includes\ez80_cpu_equates.asm  \
            E:\My_Own_Files\Coding\ez80p\Code\Includes\misc_system_equates.asm  \
            E:\My_Own_Files\Coding\ez80p\Code\Includes\prose_kernal_labels.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\RELATI~1\src\relative.asm

