SHELL = cmd.exe

#
# ZDS II Make File - comrec project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\comrec\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\comrec;..\..\..\Includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\comrec_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\comrec\Debug

build: comrec

buildall: clean comrec

relink: deltarget comrec

deltarget: 
	@if exist $(WORKDIR)\comrec.lod  \
            $(RM) $(WORKDIR)\comrec.lod
	@if exist $(WORKDIR)\comrec.hex  \
            $(RM) $(WORKDIR)\comrec.hex
	@if exist $(WORKDIR)\comrec.map  \
            $(RM) $(WORKDIR)\comrec.map

clean: 
	@if exist $(WORKDIR)\comrec.lod  \
            $(RM) $(WORKDIR)\comrec.lod
	@if exist $(WORKDIR)\comrec.hex  \
            $(RM) $(WORKDIR)\comrec.hex
	@if exist $(WORKDIR)\comrec.map  \
            $(RM) $(WORKDIR)\comrec.map
	@if exist $(WORKDIR)\comrec.obj  \
            $(RM) $(WORKDIR)\comrec.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\comrec.obj

comrec: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\comrec.obj :  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\comrec\src\comrec.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\comrec\src\comrec.asm

