SHELL = cmd.exe

#
# ZDS II Make File - sdhctest project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc;..\..\..\..\..\Includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\sdhctest_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\debug

build: sdhctest

buildall: clean sdhctest

relink: deltarget sdhctest

deltarget: 
	@if exist E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.lod  \
            $(RM) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.lod
	@if exist E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.hex  \
            $(RM) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.hex
	@if exist E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.map  \
            $(RM) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.map

clean: 
	@if exist E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.lod  \
            $(RM) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.lod
	@if exist E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.hex  \
            $(RM) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.hex
	@if exist E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.map  \
            $(RM) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\Debug\sdhctest.map
	@if exist $(WORKDIR)\testcard.obj  \
            $(RM) $(WORKDIR)\testcard.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\testcard.obj

sdhctest: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\testcard.obj :  \
            E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\src\testcard.asm  \
            E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\src\PROSE_sdcard_driver_v110.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\sdhc\src\testcard.asm

