SHELL = cmd.exe

#
# ZDS II Make File - right_border project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3;..\..\..\..\..\..\Includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\right_border_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\Debug

build: right_border

buildall: clean right_border

relink: deltarget right_border

deltarget: 
	@if exist $(WORKDIR)\right_border.lod  \
            $(RM) $(WORKDIR)\right_border.lod
	@if exist $(WORKDIR)\right_border.hex  \
            $(RM) $(WORKDIR)\right_border.hex
	@if exist $(WORKDIR)\right_border.map  \
            $(RM) $(WORKDIR)\right_border.map

clean: 
	@if exist $(WORKDIR)\right_border.lod  \
            $(RM) $(WORKDIR)\right_border.lod
	@if exist $(WORKDIR)\right_border.hex  \
            $(RM) $(WORKDIR)\right_border.hex
	@if exist $(WORKDIR)\right_border.map  \
            $(RM) $(WORKDIR)\right_border.map
	@if exist $(WORKDIR)\right_border_test1.obj  \
            $(RM) $(WORKDIR)\right_border_test1.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\right_border_test1.obj

right_border: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\right_border_test1.obj :  \
            E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\src\right_border_test1.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\src\right_border_test1.asm

