SHELL = cmd.exe

#
# ZDS II Make File - tiletest640x480 project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3;..\..\..\..\..\..\Includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\tiletest640x480_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\Debug

build: tiletest640x480

buildall: clean tiletest640x480

relink: deltarget tiletest640x480

deltarget: 
	@if exist $(WORKDIR)\test640x480.lod  \
            $(RM) $(WORKDIR)\test640x480.lod
	@if exist $(WORKDIR)\test640x480.hex  \
            $(RM) $(WORKDIR)\test640x480.hex
	@if exist $(WORKDIR)\test640x480.map  \
            $(RM) $(WORKDIR)\test640x480.map

clean: 
	@if exist $(WORKDIR)\test640x480.lod  \
            $(RM) $(WORKDIR)\test640x480.lod
	@if exist $(WORKDIR)\test640x480.hex  \
            $(RM) $(WORKDIR)\test640x480.hex
	@if exist $(WORKDIR)\test640x480.map  \
            $(RM) $(WORKDIR)\test640x480.map
	@if exist $(WORKDIR)\tiletest640x480.obj  \
            $(RM) $(WORKDIR)\tiletest640x480.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\tiletest640x480.obj

tiletest640x480: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\tiletest640x480.obj :  \
            E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\src\tiletest640x480.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\src\tiletest640x480.asm

