SHELL = cmd.exe

#
# ZDS II Make File - max_sprite project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"..;..\..\..\..\..\..\Includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\max_sprite_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\Debug

build: max_sprite

buildall: clean max_sprite

relink: deltarget max_sprite

deltarget: 
	@if exist $(WORKDIR)\max_sprite.lod  \
            $(RM) $(WORKDIR)\max_sprite.lod
	@if exist $(WORKDIR)\max_sprite.hex  \
            $(RM) $(WORKDIR)\max_sprite.hex
	@if exist $(WORKDIR)\max_sprite.map  \
            $(RM) $(WORKDIR)\max_sprite.map

clean: 
	@if exist $(WORKDIR)\max_sprite.lod  \
            $(RM) $(WORKDIR)\max_sprite.lod
	@if exist $(WORKDIR)\max_sprite.hex  \
            $(RM) $(WORKDIR)\max_sprite.hex
	@if exist $(WORKDIR)\max_sprite.map  \
            $(RM) $(WORKDIR)\max_sprite.map
	@if exist $(WORKDIR)\max_sprite.obj  \
            $(RM) $(WORKDIR)\max_sprite.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\max_sprite.obj

max_sprite: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\max_sprite.obj :  \
            E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\src\max_sprite.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\ez80p\Code\PROSEB~1\Phil\tests\AMOEBA~1\AMOEBA~3\src\max_sprite.asm

